on: [push, pull_request]
name: lint
jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup node
      uses: actions/setup-node@master
      with:
        node-version: 10.x
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
