on:
  schedule:
    # 04:44 UTC on Thursdays
    - cron: '44 4 * * 4'
  workflow_dispatch:
name: manifest
jobs:
  verify:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install dependencies
      run: npm ci
    - name: Verify manifest releases
      run: node manifest.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
