on:
  schedule:
    # 4:44 UTC daily
    - cron: '44 4 * * *'
  push:
    branches:
    - main
  pull_request: {}
name: update
jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npm ci
    - name: Update data
      run: node update-data.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Verify manifest releases
      run: node manifest.js
    - name: Monitor checks
      run: node checks.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
