on:
  schedule:
    # 6:40 UTC daily
    - cron: '40 6 * * *'
  push:
    branches:
    - master
name: update
jobs:
  update:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup node
      uses: actions/setup-node@master
      with:
        node-version: 10.x
    - name: Install dependencies
      run: npm ci
    - name: Update data
      run: node update-data.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Collect Checks stats
      run: node checks.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Collect manifest stats
      run: node manifest.js
